AWSTemplateFormatVersion: 2010-09-09
Description: Secrets template

Parameters:
  RdsMasterUsername:
    Type: String

Resources:
  # SecretsManager
  RdsMasterUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${RdsMasterUsername}"}'
        GenerateStringKey: password
        PasswordLength: 20
        ExcludeCharacters: '"@/\'

Outputs:
  RdsMasterUserSecretArn:
    Value: !Ref RdsMasterUserSecret
  GetSecretValueByCli:
    Value: !Sub >
      aws secretsmanager get-secret-value \
        --secret-id ${RdsMasterUserSecret} \
        --region ${AWS::Region} \
        --query SecretString
